"""Python binding for BSVX (Basil Voxel).

ctypes over the flat C ABI in ``src/include/bsvx_dll.h`` -- deliberately not a compiled extension,
so one build of the shared library works with whatever Python a host application ships.

    from bsvx import World

    with World.load("world_root", ignore_hash_mismatch=True) as world:
        world.set_registry_entry(1, material_id=0, flags=REGISTRY_OPAQUE, name="stone")
        world.set_voxels([(0, 0, 0), (1, 0, 0)], 1)
        world.save_dirty()

The library is located in this order: ``$BSVX_LIBRARY``, ``bsvx/bin/<platform>/``, then the
repository's ``build/`` directory.
"""

from ._lib import REQUIRED_ABI, BsvxError
from ._structs import (
    CHUNK_EMPTY,
    CHUNK_HAS_VOXELS,
    CHUNK_PRESENT,
    CODEC_AUTO,
    LAYOUT_CHUNK_ORDER,
    LAYOUT_REGION_LINEAR,
    REGISTRY_COLLIDABLE,
    REGISTRY_EMISSIVE,
    REGISTRY_OPAQUE,
    REGISTRY_SPECIAL,
    RESULT_BUFFER_TOO_SMALL,
    RESULT_CANCELLED,
    RESULT_INVALID_ARGUMENT,
    RESULT_NOT_FOUND,
    RESULT_OK,
    RESULT_RUNTIME_ERROR,
    SECTION_COLLISION,
    SECTION_DISTANCE_FIELD,
    SECTION_LIGHT,
    SECTION_METADATA,
    SECTION_SURFACE,
    SECTION_USER_BASE,
    SECTION_VOXELS,
    SEVERITY_ERROR,
    SEVERITY_INFO,
    SEVERITY_WARNING,
    VK_FORMAT_BC1_RGB_UNORM,
    VK_FORMAT_BC3_UNORM,
    VK_FORMAT_BC7_SRGB,
    VK_FORMAT_BC7_UNORM,
    VK_FORMAT_R8_UNORM,
    VK_FORMAT_R8G8_UNORM,
    VK_FORMAT_R8G8B8A8_SRGB,
    VK_FORMAT_R8G8B8A8_UNORM,
    VK_FORMAT_R16G16B16A16_SFLOAT,
    VK_FORMAT_R32G32B32A32_SFLOAT,
    AXIS_X_RIGHT_Y_UP_Z_BACK,
    AXIS_X_RIGHT_Y_UP_Z_FORWARD,
    AXIS_X_RIGHT_Z_UP_Y_FORWARD,
    MaterialDesc,
    SamplerDesc,
    SubresourceDesc,
    TextureDesc,
)
from .world import (
    ChunkInfo,
    Context,
    VfsWriter,
    axis_convention_name,
    convert_cell,
    convert_position,
    format_is_block_compressed,
    format_is_supported,
    format_subresource_size,
    GeometryDesc,
    RegistryEntry,
    SaveReport,
    TextureBuilder,
    Units,
    ValidationIssue,
    VoxelAddress,
    World,
    abi_version,
    build_info,
)

__version__ = "4.0.0"

__all__ = [
    "BsvxError",
    "ChunkInfo",
    "Context",
    "GeometryDesc",
    "MaterialDesc",
    "RegistryEntry",
    "REQUIRED_ABI",
    "SamplerDesc",
    "SaveReport",
    "SubresourceDesc",
    "TextureBuilder",
    "TextureDesc",
    "Units",
    "ValidationIssue",
    "VoxelAddress",
    "VfsWriter",
    "World",
    "abi_version",
    "axis_convention_name",
    "build_info",
    "convert_cell",
    "convert_position",
    "format_is_block_compressed",
    "format_is_supported",
    "format_subresource_size",
    "AXIS_X_RIGHT_Y_UP_Z_BACK",
    "AXIS_X_RIGHT_Y_UP_Z_FORWARD",
    "AXIS_X_RIGHT_Z_UP_Y_FORWARD",
    "VK_FORMAT_BC1_RGB_UNORM",
    "VK_FORMAT_BC3_UNORM",
    "VK_FORMAT_BC7_SRGB",
    "VK_FORMAT_BC7_UNORM",
    "VK_FORMAT_R8_UNORM",
    "VK_FORMAT_R8G8_UNORM",
    "VK_FORMAT_R16G16B16A16_SFLOAT",
    "VK_FORMAT_R32G32B32A32_SFLOAT",
    "CHUNK_EMPTY",
    "CHUNK_HAS_VOXELS",
    "CHUNK_PRESENT",
    "CODEC_AUTO",
    "LAYOUT_CHUNK_ORDER",
    "LAYOUT_REGION_LINEAR",
    "REGISTRY_COLLIDABLE",
    "REGISTRY_EMISSIVE",
    "REGISTRY_OPAQUE",
    "REGISTRY_SPECIAL",
    "RESULT_BUFFER_TOO_SMALL",
    "RESULT_CANCELLED",
    "RESULT_INVALID_ARGUMENT",
    "RESULT_NOT_FOUND",
    "RESULT_OK",
    "RESULT_RUNTIME_ERROR",
    "SECTION_COLLISION",
    "SECTION_DISTANCE_FIELD",
    "SECTION_LIGHT",
    "SECTION_METADATA",
    "SECTION_SURFACE",
    "SECTION_USER_BASE",
    "SECTION_VOXELS",
    "SEVERITY_ERROR",
    "SEVERITY_INFO",
    "SEVERITY_WARNING",
    "VK_FORMAT_R8G8B8A8_SRGB",
    "VK_FORMAT_R8G8B8A8_UNORM",
    "__version__",
]
